# Slicing y Dicing

In [1]:
import numpy as np

In [3]:
arreglo_once_cuadrado = np.arange(11)**2


In [4]:
arreglo_once_cuadrado

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [5]:
arreglo_once_cuadrado[-1]

100

In [6]:
arreglo_once_cuadrado[0:3]

array([0, 1, 4])

In [9]:
arreglo_once_cuadrado[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
arreglo_once_cuadrado[0:5:1]

array([ 0,  1,  4,  9, 16])

In [11]:
arreglo_once_cuadrado[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])