In [1]:
import numpy as np

In [2]:
paises_uno = ('Ecuador','USA','Cuba','Venezuela')

In [12]:
paises_dos= ('Brasil','China','Japon','Mexico')

In [13]:
arreglo_paises_2d = np.array([paises_uno,paises_dos])

In [14]:
arreglo_paises_2d

array([['Ecuador', 'USA', 'Cuba', 'Venezuela'],
       ['Brasil', 'China', 'Japon', 'Mexico']], dtype='<U9')

In [15]:
arreglo_paises_2d.shape

(2, 4)

In [20]:
arreglo_paises_2d.flatten().reshape(4,1,2)

array([[['Ecuador', 'USA']],

       [['Cuba', 'Venezuela']],

       [['Brasil', 'China']],

       [['Japon', 'Mexico']]], dtype='<U9')

In [17]:
arreglo_paises_2d.shape

(2, 4)

In [21]:
arreglo_paises_2d.flatten().reshape(4,-1)

array([['Ecuador', 'USA'],
       ['Cuba', 'Venezuela'],
       ['Brasil', 'China'],
       ['Japon', 'Mexico']], dtype='<U9')

In [22]:
arreglo_paises_2d.T

array([['Ecuador', 'Brasil'],
       ['USA', 'China'],
       ['Cuba', 'Japon'],
       ['Venezuela', 'Mexico']], dtype='<U9')

In [26]:
arreglo_paises = arreglo_paises_2d.flatten()

In [27]:
arreglo_paises

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brasil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [30]:
np.split(arreglo_paises,4)

[array(['Ecuador', 'USA'], dtype='<U9'),
 array(['Cuba', 'Venezuela'], dtype='<U9'),
 array(['Brasil', 'China'], dtype='<U9'),
 array(['Japon', 'Mexico'], dtype='<U9')]

In [31]:
arreglo = np.arange(12)

In [32]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
np.split(arreglo,2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [34]:
np.split(arreglo,[1,3,5,7,8])

[array([0]),
 array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7]),
 array([ 8,  9, 10, 11])]

In [36]:
arreglo_paises

array(['Ecuador', 'USA', 'Cuba', 'Venezuela', 'Brasil', 'China', 'Japon',
       'Mexico'], dtype='<U9')

In [44]:
np.hsplit(arreglo_paises_2d,4)

[array([['Ecuador'],
        ['Brasil']], dtype='<U9'), array([['USA'],
        ['China']], dtype='<U9'), array([['Cuba'],
        ['Japon']], dtype='<U9'), array([['Venezuela'],
        ['Mexico']], dtype='<U9')]

In [45]:
arr1, arr2, arr3, arr4 = np.hsplit(arreglo_paises_2d,4)

In [46]:
type(np.hsplit(arreglo_paises_2d,4))

list

In [47]:
x1, x2,x3 = [1,2,3]

In [48]:
x1

1

In [49]:
x2

2

In [51]:
x3

3

In [52]:
x1=x2=x3=1

In [53]:
x1


1

In [54]:
x2

1