In [1]:
import numpy as np


In [2]:
arreglo_np = np.array([1,2,3,4,5,6])

In [4]:
type(arreglo_np)

numpy.ndarray

In [6]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros(([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.zeros((5,2,3))
         

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
np.ones((1,4,3,6))

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.arange(3,10)#desde el [3 al 10[ en saltos de a uno

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(3,20,2)#desde el [3 al 20[ en saltos de a dos

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
arreglo_pares = np.arange(0,20,2)
print(arreglo_pares)

[ 0  2  4  6  8 10 12 14 16 18]


In [26]:
arreglo_pares.size

10

In [27]:
arreglo_pares.shape #dimension

(10,)

In [28]:
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [29]:
np.arange(24).reshape((6,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [33]:
np.arange(100000).reshape(10000,10)

array([[    0,     1,     2, ...,     7,     8,     9],
       [   10,    11,    12, ...,    17,    18,    19],
       [   20,    21,    22, ...,    27,    28,    29],
       ...,
       [99970, 99971, 99972, ..., 99977, 99978, 99979],
       [99980, 99981, 99982, ..., 99987, 99988, 99989],
       [99990, 99991, 99992, ..., 99997, 99998, 99999]])

In [34]:
a = np.array([10,10,10])

In [35]:
b= np.array((5,5,5))

In [36]:
a

array([10, 10, 10])

In [37]:
b

array([5, 5, 5])

In [38]:
a + b

array([15, 15, 15])

In [39]:
a - b

array([5, 5, 5])

In [40]:
a*b

array([50, 50, 50])

In [41]:
a/b

array([2., 2., 2.])

In [42]:
a%b

array([0, 0, 0])

In [43]:
a / 2

array([5., 5., 5.])

In [44]:
a%2

array([0, 0, 0])

In [45]:
a + 3

array([13, 13, 13])

In [46]:
a

array([10, 10, 10])

In [47]:
a*2

array([20, 20, 20])

In [51]:
arreglo_doce = np.arange(12)

In [52]:
arreglo_doce >5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [55]:
a

array([10, 10, 10])

In [57]:
A = np.arange(4).reshape(2,2)

In [58]:
A

array([[0, 1],
       [2, 3]])

In [59]:
B = np.arange(4,8).reshape((2,2))

In [60]:
B

array([[4, 5],
       [6, 7]])

In [61]:
A * B

array([[ 0,  5],
       [12, 21]])

In [62]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [64]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [69]:
resultado = np.arange(4).reshape(2,2)

In [72]:
np.dot(A,B,resultado)

array([[ 6,  7],
       [26, 31]])

In [73]:
resultado

array([[ 6,  7],
       [26, 31]])

In [74]:
arreglo_tres = np.arange(3)

In [77]:
arreglo_tres += 2

In [78]:
arreglo_tres

array([4, 5, 6])

In [81]:
arreglo_tres.min()

4

In [83]:
arreglo_tres.sum()

15

In [84]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)

In [85]:
arreglo_tres_cuatro

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
arreglo_tres_cuatro.sum()

66

In [87]:
arreglo_tres_cuatro.sum(axis = 0)

array([12, 15, 18, 21])

In [88]:
arreglo_tres_cuatro.sum(axis = 1)

array([ 6, 22, 38])

In [92]:
arreglo_mas_dim = np.arange(60).reshape(3,2,2,5)

In [93]:
arreglo_mas_dim.sum(axis = 0)

array([[[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87]],

       [[ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]]])

In [94]:
arreglo_mas_dim

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]],


       [[[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]]])