In [1]:
import numpy as np

In [19]:
path = './data/salarios.csv'
arreglo_salarios = np.genfromtxt(path,delimiter=',')


In [20]:
arreglo_salarios

array([[ 200.,  300.,  400.,  500.,  600.,  700.,  800.,  900.],
       [ 233.,  345.,  654.,  888.,  123.,  878.,   98., 4443.]])

In [21]:
arreglo_salarios=arreglo_salarios*1.1

In [22]:
arreglo_salarios

array([[ 220. ,  330. ,  440. ,  550. ,  660. ,  770. ,  880. ,  990. ],
       [ 256.3,  379.5,  719.4,  976.8,  135.3,  965.8,  107.8, 4887.3]])

In [25]:
np.savetxt(path,arreglo_salarios,delimiter=",",fmt= '%4d')

In [26]:
arreglo_salarios

array([[ 220. ,  330. ,  440. ,  550. ,  660. ,  770. ,  880. ,  990. ],
       [ 256.3,  379.5,  719.4,  976.8,  135.3,  965.8,  107.8, 4887.3]])