In [1]:
import numpy as np

In [2]:
angulos_cero_noventa = np.array((0,30,45,60,90))

In [3]:
angulos_radianes = angulos_cero_noventa*np.pi/180

In [4]:
angulos_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(angulos_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.cos(angulos_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [7]:
np.arctan(angulos_radianes)

array([0.        , 0.48234791, 0.66577375, 0.80844879, 1.00388482])

In [8]:
arreglo_random = np.random.rand(10)

In [10]:
arreglo_random = arreglo_random*10

In [11]:
arreglo_random

array([3.73825817, 5.32885689, 3.30350331, 4.62333324, 7.91813768,
       0.34405301, 5.99184201, 3.29086474, 4.43558663, 0.26523247])

In [22]:
arreglo_random_int = np.random.randint(0,100,20)

In [23]:
arreglo_random_int

array([45, 33, 65, 87, 84, 87, 33, 30, 73, 44, 17, 84,  8, 20, 73, 81,  8,
       13, 11, 65])

In [24]:
arreglo_random_int.mean()

48.05

In [25]:
np.median(arreglo_random_int)

44.5

In [26]:
np.std(arreglo_random_int)

29.05937886466261

In [27]:
np.var(arreglo_random_int)

844.4475