In [13]:
def a (**b):
    print(f"{b}")
    


In [14]:
a

<function __main__.a(**b)>

In [15]:
a(nombre=3,juan=4)

{'nombre': 3, 'juan': 4}


In [17]:
diccionario = {'nombre':'Michael','edad':'23'}

In [26]:
diccionario

{'nombre': 'Michael', 'edad': '23'}

In [27]:
type(diccionario)

dict

In [28]:
int(False)

0

In [33]:
adrian = {"edado":29}

In [38]:
adrian.update({'s':2,'m':3})

In [39]:
adrian

{'edado': 29, 'nombre': 'Michael', 'edad': '23', 's': 2, 'm': 3}

In [41]:
nombre = {'jose':"joe"}

In [42]:
nombre

{'jose': 'joe'}

In [43]:
n = {1,2,3,4,5,"f",'d'}

In [44]:
type(n)

set

In [45]:
m = (1,2,3,4)

In [46]:
type(m)

tuple

In [52]:
try:
    print()
except Exception as err:
        print('asd')

In [54]:
a = None

In [55]:
a

In [56]:
type(a)

NoneType

In [60]:
def j (a,b):
    print(a)

In [61]:
j(a="a",b="c")

a


In [70]:
def f(b,c,d="s"):
    def x():
        return b+c
    def u():
        return{
            's':3
        }[d]
    x()

In [73]:
f(1,2)


In [74]:
arr = [1,2,3]

In [75]:
arr.pop(-1)

3

In [76]:
arr


[1, 2]

In [77]:
arr.pop(-3)

IndexError: pop index out of range

In [80]:
michael = {'edad':12,'sueldo':33}


In [86]:
michael.items()

dict_items([('edad', 12), ('sueldo', 33)])

In [87]:
def g (n):
    c= open(n)

In [89]:
g(1)

OSError: [WinError 6] Controlador no válido

# EXAMEN

In [90]:
import numpy as np
import pandas as pd

In [98]:
arr = np.zeros(10)

In [99]:
arr[5] = 1

In [101]:
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [108]:
arr_cinc = np.arange(1,51)

In [109]:
arr_cinc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [134]:
arr_cinc_ivertido = arr_cinc[-1:-51:-1]

In [135]:
print(arr_cinc_ivertido)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [136]:
arr_tres = np.arange(0,9).reshape(3,3)

In [137]:
arr_tres

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [138]:
arr_ident = np.eye(3,3)

In [139]:
arr_ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
arr_ident = np.identity(3)

In [141]:
arr_ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
arr_p = np.arange(4)

In [143]:
arr_p

array([0, 1, 2, 3])

In [171]:
arr_rand = np.random.randint(1,20,(10,2))

In [172]:
arr_rand

array([[14,  4],
       [ 3,  2],
       [ 5,  3],
       [14,  9],
       [17, 17],
       [18,  8],
       [ 8, 12],
       [18,  9],
       [13, 13],
       [12,  8]])

In [190]:
arr_m = np.arange(100).reshape(10,10)

In [191]:
arr_m 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [189]:
print('max:',arr_m.max())
print('min:',arr_m.min())

max: 99
min: 0


In [222]:
mat_ran_50 = np.random.randint(1,3,(5,2))

In [223]:
mat_ran_50

array([[2, 2],
       [2, 1],
       [1, 2],
       [1, 1],
       [2, 2]])

In [230]:
cuales,cuntos = np.unique(mat_ran_50, axis = 0, return_counts = True)

In [225]:
cuantos

array([1, 2])

In [226]:
cuales

array([[1, 1],
       [1, 2],
       [2, 1],
       [2, 2]])

In [378]:
def indices_no_repetidos(arr):
    unique, index, count = np.unique(arr, axis=0, return_index=True,return_counts=True)
    indices = []
    contador = []
    cruzada = []
    aux = 0
    for c in count:
        if c == 1:
            cruzada.append(index[aux])
            aux = aux +1
    return cruzada


In [379]:
unique

array([[1, 1],
       [1, 2],
       [2, 1],
       [2, 2]])

In [380]:
index

array([3, 2, 1, 0], dtype=int64)

In [381]:
count

array([1, 1, 1, 2], dtype=int64)

In [389]:
mat_ran_50

array([[2, 2],
       [2, 1],
       [1, 2],
       [1, 1],
       [2, 2]])

In [384]:
mis_indices = indices_no_repetidos(mat_ran_50)

print(micruzada)


[3, 2, 1]


In [385]:
type(mis_indices)

list

In [387]:
print(mat_ran_50)

[[2 2]
 [2 1]
 [1 2]
 [1 1]
 [2 2]]


In [390]:
mat_ran_50

array([[2, 2],
       [2, 1],
       [1, 2],
       [1, 1],
       [2, 2]])

In [394]:
a = np.array([[[1,2,3],[3,2,1]],[[2,3,4],[3,2,1]]])

In [395]:
bi = np.random.randint(0,5,(3,2,2))

In [396]:
bi

array([[[4, 2],
        [1, 3]],

       [[4, 2],
        [0, 3]],

       [[2, 0],
        [3, 3]]])

In [397]:
bi_ind = indices_no_repetidos(bi)

In [398]:
bi_ind

[2, 1, 0]

In [399]:
a_ind = indices_no_repetidos(a)

In [400]:
a_ind

[0, 1]

In [411]:
a.shape(0)

TypeError: 'tuple' object is not callable

In [406]:
a.reshape(4,3)

array([[1, 2, 3],
       [3, 2, 1],
       [2, 3, 4],
       [3, 2, 1]])

In [410]:
a
    

array([[[1, 2, 3],
        [3, 2, 1]],

       [[2, 3, 4],
        [3, 2, 1]]])

In [408]:
a.size

12